http_params_dict = {
    "api_containers_run": {
        "image": {"default": None, "type": "str"},
        "command": {"default": None, "type": "str"},
        "auto_remove": {"default": None, "type": "bool"},
        "blkio_weight_device": {"default": None, "type": "dict"},
        "blkio_weight": {"default": None, "type": "int"},
        "cap_add": {"default": None, "type": "str"},
        "cap_drop": {"default": None, "type": "str"},
        "cgroup_parent": {"default": None, "type": "str"},
        "cpu_count": {"default": None, "type": "int"},
        "cpu_percent": {"default": None, "type": "int"},
        "cpu_period": {"default": None, "type": "int"},
        "cpu_quota": {"default": None, "type": "int"},
        "cpu_rt_period": {"default": None, "type": "int"},
        "cpu_rt_runtime": {"default": None, "type": "int"},
        "cpu_shares": {"default": None, "type": "int"},
        "cpuset_cpus": {"default": None, "type": "int"},
        "cpuset_mems": {"default": None, "type": "str"},
        "detach": {"default": True, "type": "bool"},
        "device_cgroup_rules": {"default": None, "type": "list"},
        "device_read_bps": {"default": None, "type": "dict"},
        "device_read_iops": {"default": None, "type": "int"},
        "device_write_bps": {"default": None, "type": "int"},
        "device_write_iops": {"default": None, "type": "int"},
        "devices": {"default": None, "type": "list"},
        "dns": {"default": None, "type": "list"},
        "dns_opt": {"default": None, "type": "list"},
        "dns_search": {"default": None, "type": "list"},
        "domainname": {"default": None, "type": "str"},
        "entrypoint": {"default": None, "type": "str"},
        "environment": {"default": None, "type": "dict"},
        "extra_hosts": {"default": None, "type": "dict"},
        "healthcheck": {"default": None, "type": "dict"},
        "hostname": {"default": None, "type": "str"},
        "init": {"default": None, "type": "bool"},
        "init_path": {"default": None, "type": "str"},
        "ipc_mode": {"default": None, "type": "str"},
        "isolation": {"default": None, "type": "str"},
        "kernel_memory": {"default": None, "type": "int"},
        "labels": {"default": None, "type": "dict"},
        "links": {"default": None, "type": "dict"},
        # "log_config": {"default": None ,"type": logConfic},
        "lxc_conf": {"default": None, "type": "dict"},
        "mac_address": {"default": None, "type": "str"},
        "mem_limit": {"default": None, "type": "int"},
        "mem_reservation": {"default": None, "type": "int"},
        "mem_swappiness": {"default": None, "type": "int"},
        "memswap_limit": {"default": None, "type": "str"},
        "mounts": {"default": None, "type": "list"},
        "name": {"default": None, "type": "str"},
        "nano_cpus": {"default": None, "type": "int"},
        "network": {"default": None, "type": "str"},
        "network_disabled": {"default": None, "type": "bool"},
        "network_mode": {"default": None, "type": "str"},
        "oom_kill_disable": {"default": None, "type": "bool"},
        "oom_score_adj": {"default": None, "type": "int"},
        "pid_mode": {"default": None, "type": "str"},
        "pids_limit": {"default": None, "type": "int"},
        "platform": {"default": None, "type": "str"},
        "pids_limit": {"default": None, "type": "int"},
        "ports": {"default": None, "type": "dict"},
        "privileged": {"default": None, "type": "bool"},
        "publish_all_ports": {"default": None, "type": "bool"},
        "read_only": {"default": None, "type": "bool"},
        "remove": {"default": False, "type": "bool"},
        "restart_policy": {"default": None, "type": "dict"},
        "runtime": {"default": None, "type": "str"},
        "security_opt": {"default": None, "type": "list"},
        "shm_size": {"default": None, "type": "str"},
        "stdin_open": {"default": None, "type": "bool"},
        "stdout": {"default": True, "type": "bool"},
        "stderr": {"default": False, "type": "bool"},
        "stop_signal": {"default": None, "type": "str"},
        "storage_opt": {"default": None, "type": "dict"},
        "stream": {"default": False, "type": "bool"},
        "sysctls": {"default": None, "type": "dict"},
        "tmpfs": {"default": None, "type": "dict"},
        "tty": {"default": None, "type": "bool"},
        "ulimits": {"default": None, "type": "list"},
        "use_config_proxy": {"default": None, "type": "bool"},
        "user": {"default": None, "type": "str"},
        "userns_mode": {"default": None, "type": "str"},
        "uts_mode": {"default": None, "type": "str"},
        "version": {"default": None, "type": "str"},
        "volume_driver": {"default": None, "type": "str"},
        "volumes": {"default": None, "type": "dict"},
        "volumes_from": {"default": None, "type": "list"},
        "working_dir": {"default": None, "type": "str"},
    },
    "api_containers_list": {"all": {"default": False, "type": "bool"},
                            "since": {"default": None, "type": "str"},
                            "before": {"default": None, "type": "str"},
                            "limit": {"default": None, "type": "str"},
                            "filters": {"default": None, "type": "dict"},
                            "sparse": {"default": False, "type": "bool"},
                            "ignore_removed": {"default": False, "type": "bool"}
                            },
    "api_container_rename": {"name": {"default": None, "type": "str"}},
    "api_container_top": {"ps_args": {"default": None, "type": "str"}},
    "api_container_remove": {"v": {"default": False, "type": "bool"},
                             "link": {"default": False, "type": "str"},
                             "force": {"default": False, "type": "str"}
                             },
    "api_container_kill": {"signal": {"default": None, "type": "int"}},
    "api_images_prune": {"filters": {"default": None, "type": "dict"}},
    "api_images_search": {
        "term": {"default": None, "type": "str"},
        "limit": {"default": None, "type": "int"}
    },
    "api_image_tag": {
        "repository": {"default": None, "type": "str"},
        "tag": {"default": None, "type": "str"},
    }
}
